version: '3'
services:
  health-checker:
    image: sinawic/service-health-checker
    ports:
      - 3000:3000
    volumes:
      - ./upstreams.json:/app/upstreams.json
    restart: always
    build: ./
